//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18449
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.18449。
// 
#pragma warning disable 1591

namespace digiEAR_api_sample.DigiEarSearch {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DEsearchSoap", Namespace="http://cyberasiatech.com/digiEAR/XmlWebServices/")]
    public partial class DEsearch : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback digiEAR_searchOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_search2OperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_searchOpenHandleOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_searchCloseHandleOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_searchCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_searchGetStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_searchAllowedOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_ValidateQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerGetAllValidSoundBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerOpenHandleOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerCloseHandleOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerInitialSoundBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerGetSoundByteSequenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerGetAllSoundByteSequencesOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerGetSoundByteSequenceCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerGetWordCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerExamineSearchResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerEvaluateSoundBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerFindOptimalOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_hAllProOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_QueryAnalyzerAllowedOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_GetPatInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DEsearch() {
            this.Url = global::digiEAR_api_sample.Properties.Settings.Default.digiEAR_api_sample_DigiEarSearch_DEsearch;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event digiEAR_searchCompletedEventHandler digiEAR_searchCompleted;
        
        /// <remarks/>
        public event digiEAR_search2CompletedEventHandler digiEAR_search2Completed;
        
        /// <remarks/>
        public event digiEAR_searchOpenHandleCompletedEventHandler digiEAR_searchOpenHandleCompleted;
        
        /// <remarks/>
        public event digiEAR_searchCloseHandleCompletedEventHandler digiEAR_searchCloseHandleCompleted;
        
        /// <remarks/>
        public event digiEAR_searchCancelCompletedEventHandler digiEAR_searchCancelCompleted;
        
        /// <remarks/>
        public event digiEAR_searchGetStatusCompletedEventHandler digiEAR_searchGetStatusCompleted;
        
        /// <remarks/>
        public event digiEAR_searchAllowedCompletedEventHandler digiEAR_searchAllowedCompleted;
        
        /// <remarks/>
        public event digiEAR_ValidateQueryCompletedEventHandler digiEAR_ValidateQueryCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerGetAllValidSoundBytesCompletedEventHandler digiEAR_QueryAnalyzerGetAllValidSoundBytesCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerOpenHandleCompletedEventHandler digiEAR_QueryAnalyzerOpenHandleCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerCloseHandleCompletedEventHandler digiEAR_QueryAnalyzerCloseHandleCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerInitialSoundBytesCompletedEventHandler digiEAR_QueryAnalyzerInitialSoundBytesCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerGetSoundByteSequenceCompletedEventHandler digiEAR_QueryAnalyzerGetSoundByteSequenceCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompletedEventHandler digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompletedEventHandler digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerGetWordCountCompletedEventHandler digiEAR_QueryAnalyzerGetWordCountCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerExamineSearchResultCompletedEventHandler digiEAR_QueryAnalyzerExamineSearchResultCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerEvaluateSoundBytesCompletedEventHandler digiEAR_QueryAnalyzerEvaluateSoundBytesCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerFindOptimalCompletedEventHandler digiEAR_QueryAnalyzerFindOptimalCompleted;
        
        /// <remarks/>
        public event digiEAR_hAllProCompletedEventHandler digiEAR_hAllProCompleted;
        
        /// <remarks/>
        public event digiEAR_QueryAnalyzerAllowedCompletedEventHandler digiEAR_QueryAnalyzerAllowedCompleted;
        
        /// <remarks/>
        public event digiEAR_GetPatInfoCompletedEventHandler digiEAR_GetPatInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_search", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet digiEAR_search(int imaxResults, System.Data.DataSet searchDS, int ihSearch) {
            object[] results = this.Invoke("digiEAR_search", new object[] {
                        imaxResults,
                        searchDS,
                        ihSearch});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_searchAsync(int imaxResults, System.Data.DataSet searchDS, int ihSearch) {
            this.digiEAR_searchAsync(imaxResults, searchDS, ihSearch, null);
        }
        
        /// <remarks/>
        public void digiEAR_searchAsync(int imaxResults, System.Data.DataSet searchDS, int ihSearch, object userState) {
            if ((this.digiEAR_searchOperationCompleted == null)) {
                this.digiEAR_searchOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_searchOperationCompleted);
            }
            this.InvokeAsync("digiEAR_search", new object[] {
                        imaxResults,
                        searchDS,
                        ihSearch}, this.digiEAR_searchOperationCompleted, userState);
        }
        
        private void OndigiEAR_searchOperationCompleted(object arg) {
            if ((this.digiEAR_searchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_searchCompleted(this, new digiEAR_searchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_search2", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet digiEAR_search2(int imaxResults, System.Data.DataSet searchDS, int ihSearch) {
            object[] results = this.Invoke("digiEAR_search2", new object[] {
                        imaxResults,
                        searchDS,
                        ihSearch});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_search2Async(int imaxResults, System.Data.DataSet searchDS, int ihSearch) {
            this.digiEAR_search2Async(imaxResults, searchDS, ihSearch, null);
        }
        
        /// <remarks/>
        public void digiEAR_search2Async(int imaxResults, System.Data.DataSet searchDS, int ihSearch, object userState) {
            if ((this.digiEAR_search2OperationCompleted == null)) {
                this.digiEAR_search2OperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_search2OperationCompleted);
            }
            this.InvokeAsync("digiEAR_search2", new object[] {
                        imaxResults,
                        searchDS,
                        ihSearch}, this.digiEAR_search2OperationCompleted, userState);
        }
        
        private void OndigiEAR_search2OperationCompleted(object arg) {
            if ((this.digiEAR_search2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_search2Completed(this, new digiEAR_search2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_searchOpenHandle", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_searchOpenHandle(out int ihSearch) {
            object[] results = this.Invoke("digiEAR_searchOpenHandle", new object[0]);
            ihSearch = ((int)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_searchOpenHandleAsync() {
            this.digiEAR_searchOpenHandleAsync(null);
        }
        
        /// <remarks/>
        public void digiEAR_searchOpenHandleAsync(object userState) {
            if ((this.digiEAR_searchOpenHandleOperationCompleted == null)) {
                this.digiEAR_searchOpenHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_searchOpenHandleOperationCompleted);
            }
            this.InvokeAsync("digiEAR_searchOpenHandle", new object[0], this.digiEAR_searchOpenHandleOperationCompleted, userState);
        }
        
        private void OndigiEAR_searchOpenHandleOperationCompleted(object arg) {
            if ((this.digiEAR_searchOpenHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_searchOpenHandleCompleted(this, new digiEAR_searchOpenHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_searchCloseHandle", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_searchCloseHandle(int ihSearch) {
            object[] results = this.Invoke("digiEAR_searchCloseHandle", new object[] {
                        ihSearch});
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_searchCloseHandleAsync(int ihSearch) {
            this.digiEAR_searchCloseHandleAsync(ihSearch, null);
        }
        
        /// <remarks/>
        public void digiEAR_searchCloseHandleAsync(int ihSearch, object userState) {
            if ((this.digiEAR_searchCloseHandleOperationCompleted == null)) {
                this.digiEAR_searchCloseHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_searchCloseHandleOperationCompleted);
            }
            this.InvokeAsync("digiEAR_searchCloseHandle", new object[] {
                        ihSearch}, this.digiEAR_searchCloseHandleOperationCompleted, userState);
        }
        
        private void OndigiEAR_searchCloseHandleOperationCompleted(object arg) {
            if ((this.digiEAR_searchCloseHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_searchCloseHandleCompleted(this, new digiEAR_searchCloseHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_searchCancel", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_searchCancel(int ihSearch) {
            object[] results = this.Invoke("digiEAR_searchCancel", new object[] {
                        ihSearch});
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_searchCancelAsync(int ihSearch) {
            this.digiEAR_searchCancelAsync(ihSearch, null);
        }
        
        /// <remarks/>
        public void digiEAR_searchCancelAsync(int ihSearch, object userState) {
            if ((this.digiEAR_searchCancelOperationCompleted == null)) {
                this.digiEAR_searchCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_searchCancelOperationCompleted);
            }
            this.InvokeAsync("digiEAR_searchCancel", new object[] {
                        ihSearch}, this.digiEAR_searchCancelOperationCompleted, userState);
        }
        
        private void OndigiEAR_searchCancelOperationCompleted(object arg) {
            if ((this.digiEAR_searchCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_searchCancelCompleted(this, new digiEAR_searchCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_searchGetStatus", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_searchGetStatus(int ihSearch, out float fPercent) {
            object[] results = this.Invoke("digiEAR_searchGetStatus", new object[] {
                        ihSearch});
            fPercent = ((float)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_searchGetStatusAsync(int ihSearch) {
            this.digiEAR_searchGetStatusAsync(ihSearch, null);
        }
        
        /// <remarks/>
        public void digiEAR_searchGetStatusAsync(int ihSearch, object userState) {
            if ((this.digiEAR_searchGetStatusOperationCompleted == null)) {
                this.digiEAR_searchGetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_searchGetStatusOperationCompleted);
            }
            this.InvokeAsync("digiEAR_searchGetStatus", new object[] {
                        ihSearch}, this.digiEAR_searchGetStatusOperationCompleted, userState);
        }
        
        private void OndigiEAR_searchGetStatusOperationCompleted(object arg) {
            if ((this.digiEAR_searchGetStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_searchGetStatusCompleted(this, new digiEAR_searchGetStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_searchAllowed", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool digiEAR_searchAllowed() {
            object[] results = this.Invoke("digiEAR_searchAllowed", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_searchAllowedAsync() {
            this.digiEAR_searchAllowedAsync(null);
        }
        
        /// <remarks/>
        public void digiEAR_searchAllowedAsync(object userState) {
            if ((this.digiEAR_searchAllowedOperationCompleted == null)) {
                this.digiEAR_searchAllowedOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_searchAllowedOperationCompleted);
            }
            this.InvokeAsync("digiEAR_searchAllowed", new object[0], this.digiEAR_searchAllowedOperationCompleted, userState);
        }
        
        private void OndigiEAR_searchAllowedOperationCompleted(object arg) {
            if ((this.digiEAR_searchAllowedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_searchAllowedCompleted(this, new digiEAR_searchAllowedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_ValidateQuery", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_ValidateQuery(string proName, byte langVersion, string strQuery, out string badString) {
            object[] results = this.Invoke("digiEAR_ValidateQuery", new object[] {
                        proName,
                        langVersion,
                        strQuery});
            badString = ((string)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_ValidateQueryAsync(string proName, byte langVersion, string strQuery) {
            this.digiEAR_ValidateQueryAsync(proName, langVersion, strQuery, null);
        }
        
        /// <remarks/>
        public void digiEAR_ValidateQueryAsync(string proName, byte langVersion, string strQuery, object userState) {
            if ((this.digiEAR_ValidateQueryOperationCompleted == null)) {
                this.digiEAR_ValidateQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_ValidateQueryOperationCompleted);
            }
            this.InvokeAsync("digiEAR_ValidateQuery", new object[] {
                        proName,
                        langVersion,
                        strQuery}, this.digiEAR_ValidateQueryOperationCompleted, userState);
        }
        
        private void OndigiEAR_ValidateQueryOperationCompleted(object arg) {
            if ((this.digiEAR_ValidateQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_ValidateQueryCompleted(this, new digiEAR_ValidateQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerGetAllValidS" +
            "oundBytes", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string digiEAR_QueryAnalyzerGetAllValidSoundBytes(string proName, byte langVersion) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerGetAllValidSoundBytes", new object[] {
                        proName,
                        langVersion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetAllValidSoundBytesAsync(string proName, byte langVersion) {
            this.digiEAR_QueryAnalyzerGetAllValidSoundBytesAsync(proName, langVersion, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetAllValidSoundBytesAsync(string proName, byte langVersion, object userState) {
            if ((this.digiEAR_QueryAnalyzerGetAllValidSoundBytesOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerGetAllValidSoundBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerGetAllValidSoundBytesOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerGetAllValidSoundBytes", new object[] {
                        proName,
                        langVersion}, this.digiEAR_QueryAnalyzerGetAllValidSoundBytesOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerGetAllValidSoundBytesOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerGetAllValidSoundBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerGetAllValidSoundBytesCompleted(this, new digiEAR_QueryAnalyzerGetAllValidSoundBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerOpenHandle", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerOpenHandle(string proName, byte langVersion, string strQuery, uint nMaxPro, out int ihQanalyzer) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerOpenHandle", new object[] {
                        proName,
                        langVersion,
                        strQuery,
                        nMaxPro});
            ihQanalyzer = ((int)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerOpenHandleAsync(string proName, byte langVersion, string strQuery, uint nMaxPro) {
            this.digiEAR_QueryAnalyzerOpenHandleAsync(proName, langVersion, strQuery, nMaxPro, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerOpenHandleAsync(string proName, byte langVersion, string strQuery, uint nMaxPro, object userState) {
            if ((this.digiEAR_QueryAnalyzerOpenHandleOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerOpenHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerOpenHandleOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerOpenHandle", new object[] {
                        proName,
                        langVersion,
                        strQuery,
                        nMaxPro}, this.digiEAR_QueryAnalyzerOpenHandleOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerOpenHandleOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerOpenHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerOpenHandleCompleted(this, new digiEAR_QueryAnalyzerOpenHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerCloseHandle", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerCloseHandle(int ihQanalyzer) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerCloseHandle", new object[] {
                        ihQanalyzer});
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerCloseHandleAsync(int ihQanalyzer) {
            this.digiEAR_QueryAnalyzerCloseHandleAsync(ihQanalyzer, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerCloseHandleAsync(int ihQanalyzer, object userState) {
            if ((this.digiEAR_QueryAnalyzerCloseHandleOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerCloseHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerCloseHandleOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerCloseHandle", new object[] {
                        ihQanalyzer}, this.digiEAR_QueryAnalyzerCloseHandleOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerCloseHandleOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerCloseHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerCloseHandleCompleted(this, new digiEAR_QueryAnalyzerCloseHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerInitialSound" +
            "Bytes", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerInitialSoundBytes(int ihQanalyzer, out string strQueryString, out string strSoundBytes) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerInitialSoundBytes", new object[] {
                        ihQanalyzer});
            strQueryString = ((string)(results[1]));
            strSoundBytes = ((string)(results[2]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerInitialSoundBytesAsync(int ihQanalyzer) {
            this.digiEAR_QueryAnalyzerInitialSoundBytesAsync(ihQanalyzer, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerInitialSoundBytesAsync(int ihQanalyzer, object userState) {
            if ((this.digiEAR_QueryAnalyzerInitialSoundBytesOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerInitialSoundBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerInitialSoundBytesOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerInitialSoundBytes", new object[] {
                        ihQanalyzer}, this.digiEAR_QueryAnalyzerInitialSoundBytesOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerInitialSoundBytesOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerInitialSoundBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerInitialSoundBytesCompleted(this, new digiEAR_QueryAnalyzerInitialSoundBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerGetSoundByte" +
            "Sequence", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerGetSoundByteSequence(int ihQanalyzer, int index, out string strQueryString, out string strSoundBytes, out bool binDict, out float fScore) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerGetSoundByteSequence", new object[] {
                        ihQanalyzer,
                        index});
            strQueryString = ((string)(results[1]));
            strSoundBytes = ((string)(results[2]));
            binDict = ((bool)(results[3]));
            fScore = ((float)(results[4]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetSoundByteSequenceAsync(int ihQanalyzer, int index) {
            this.digiEAR_QueryAnalyzerGetSoundByteSequenceAsync(ihQanalyzer, index, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetSoundByteSequenceAsync(int ihQanalyzer, int index, object userState) {
            if ((this.digiEAR_QueryAnalyzerGetSoundByteSequenceOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerGetSoundByteSequenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerGetSoundByteSequenceOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerGetSoundByteSequence", new object[] {
                        ihQanalyzer,
                        index}, this.digiEAR_QueryAnalyzerGetSoundByteSequenceOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerGetSoundByteSequenceOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerGetSoundByteSequenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerGetSoundByteSequenceCompleted(this, new digiEAR_QueryAnalyzerGetSoundByteSequenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerGetAllSoundB" +
            "yteSequences", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerGetAllSoundByteSequences(int ihQanalyzer, uint nMaxPro, out System.Data.DataSet evaluateDS) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerGetAllSoundByteSequences", new object[] {
                        ihQanalyzer,
                        nMaxPro});
            evaluateDS = ((System.Data.DataSet)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetAllSoundByteSequencesAsync(int ihQanalyzer, uint nMaxPro) {
            this.digiEAR_QueryAnalyzerGetAllSoundByteSequencesAsync(ihQanalyzer, nMaxPro, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetAllSoundByteSequencesAsync(int ihQanalyzer, uint nMaxPro, object userState) {
            if ((this.digiEAR_QueryAnalyzerGetAllSoundByteSequencesOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerGetAllSoundByteSequencesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerGetAllSoundByteSequencesOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerGetAllSoundByteSequences", new object[] {
                        ihQanalyzer,
                        nMaxPro}, this.digiEAR_QueryAnalyzerGetAllSoundByteSequencesOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerGetAllSoundByteSequencesOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompleted(this, new digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerGetSoundByte" +
            "SequenceCount", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public uint digiEAR_QueryAnalyzerGetSoundByteSequenceCount(int ihQanalyzer) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerGetSoundByteSequenceCount", new object[] {
                        ihQanalyzer});
            return ((uint)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetSoundByteSequenceCountAsync(int ihQanalyzer) {
            this.digiEAR_QueryAnalyzerGetSoundByteSequenceCountAsync(ihQanalyzer, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetSoundByteSequenceCountAsync(int ihQanalyzer, object userState) {
            if ((this.digiEAR_QueryAnalyzerGetSoundByteSequenceCountOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerGetSoundByteSequenceCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerGetSoundByteSequenceCountOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerGetSoundByteSequenceCount", new object[] {
                        ihQanalyzer}, this.digiEAR_QueryAnalyzerGetSoundByteSequenceCountOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerGetSoundByteSequenceCountOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompleted(this, new digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerGetWordCount" +
            "", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public uint digiEAR_QueryAnalyzerGetWordCount(int ihQanalyzer) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerGetWordCount", new object[] {
                        ihQanalyzer});
            return ((uint)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetWordCountAsync(int ihQanalyzer) {
            this.digiEAR_QueryAnalyzerGetWordCountAsync(ihQanalyzer, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerGetWordCountAsync(int ihQanalyzer, object userState) {
            if ((this.digiEAR_QueryAnalyzerGetWordCountOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerGetWordCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerGetWordCountOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerGetWordCount", new object[] {
                        ihQanalyzer}, this.digiEAR_QueryAnalyzerGetWordCountOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerGetWordCountOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerGetWordCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerGetWordCountCompleted(this, new digiEAR_QueryAnalyzerGetWordCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerExamineSearc" +
            "hResult", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerExamineSearchResult(int ihQanalyzer, string patString, string strQuery, float fScore, int nStartTime, int nEndTime, out System.Data.DataSet examineResultDS) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerExamineSearchResult", new object[] {
                        ihQanalyzer,
                        patString,
                        strQuery,
                        fScore,
                        nStartTime,
                        nEndTime});
            examineResultDS = ((System.Data.DataSet)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerExamineSearchResultAsync(int ihQanalyzer, string patString, string strQuery, float fScore, int nStartTime, int nEndTime) {
            this.digiEAR_QueryAnalyzerExamineSearchResultAsync(ihQanalyzer, patString, strQuery, fScore, nStartTime, nEndTime, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerExamineSearchResultAsync(int ihQanalyzer, string patString, string strQuery, float fScore, int nStartTime, int nEndTime, object userState) {
            if ((this.digiEAR_QueryAnalyzerExamineSearchResultOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerExamineSearchResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerExamineSearchResultOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerExamineSearchResult", new object[] {
                        ihQanalyzer,
                        patString,
                        strQuery,
                        fScore,
                        nStartTime,
                        nEndTime}, this.digiEAR_QueryAnalyzerExamineSearchResultOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerExamineSearchResultOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerExamineSearchResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerExamineSearchResultCompleted(this, new digiEAR_QueryAnalyzerExamineSearchResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerEvaluateSoun" +
            "dBytes", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerEvaluateSoundBytes(int ihQanalyzer, uint nMaxPro, System.Data.DataSet clipsDS, out System.Data.DataSet evaluateDS) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerEvaluateSoundBytes", new object[] {
                        ihQanalyzer,
                        nMaxPro,
                        clipsDS});
            evaluateDS = ((System.Data.DataSet)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerEvaluateSoundBytesAsync(int ihQanalyzer, uint nMaxPro, System.Data.DataSet clipsDS) {
            this.digiEAR_QueryAnalyzerEvaluateSoundBytesAsync(ihQanalyzer, nMaxPro, clipsDS, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerEvaluateSoundBytesAsync(int ihQanalyzer, uint nMaxPro, System.Data.DataSet clipsDS, object userState) {
            if ((this.digiEAR_QueryAnalyzerEvaluateSoundBytesOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerEvaluateSoundBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerEvaluateSoundBytesOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerEvaluateSoundBytes", new object[] {
                        ihQanalyzer,
                        nMaxPro,
                        clipsDS}, this.digiEAR_QueryAnalyzerEvaluateSoundBytesOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerEvaluateSoundBytesOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerEvaluateSoundBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerEvaluateSoundBytesCompleted(this, new digiEAR_QueryAnalyzerEvaluateSoundBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerFindOptimal", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_QueryAnalyzerFindOptimal(int ihQanalyzer, System.Data.DataSet clipsDS, uint nMaxPro, out int ihProTerms) {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerFindOptimal", new object[] {
                        ihQanalyzer,
                        clipsDS,
                        nMaxPro});
            ihProTerms = ((int)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerFindOptimalAsync(int ihQanalyzer, System.Data.DataSet clipsDS, uint nMaxPro) {
            this.digiEAR_QueryAnalyzerFindOptimalAsync(ihQanalyzer, clipsDS, nMaxPro, null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerFindOptimalAsync(int ihQanalyzer, System.Data.DataSet clipsDS, uint nMaxPro, object userState) {
            if ((this.digiEAR_QueryAnalyzerFindOptimalOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerFindOptimalOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerFindOptimalOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerFindOptimal", new object[] {
                        ihQanalyzer,
                        clipsDS,
                        nMaxPro}, this.digiEAR_QueryAnalyzerFindOptimalOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerFindOptimalOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerFindOptimalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerFindOptimalCompleted(this, new digiEAR_QueryAnalyzerFindOptimalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_hAllPro", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet digiEAR_hAllPro() {
            object[] results = this.Invoke("digiEAR_hAllPro", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_hAllProAsync() {
            this.digiEAR_hAllProAsync(null);
        }
        
        /// <remarks/>
        public void digiEAR_hAllProAsync(object userState) {
            if ((this.digiEAR_hAllProOperationCompleted == null)) {
                this.digiEAR_hAllProOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_hAllProOperationCompleted);
            }
            this.InvokeAsync("digiEAR_hAllPro", new object[0], this.digiEAR_hAllProOperationCompleted, userState);
        }
        
        private void OndigiEAR_hAllProOperationCompleted(object arg) {
            if ((this.digiEAR_hAllProCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_hAllProCompleted(this, new digiEAR_hAllProCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_QueryAnalyzerAllowed", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool digiEAR_QueryAnalyzerAllowed() {
            object[] results = this.Invoke("digiEAR_QueryAnalyzerAllowed", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerAllowedAsync() {
            this.digiEAR_QueryAnalyzerAllowedAsync(null);
        }
        
        /// <remarks/>
        public void digiEAR_QueryAnalyzerAllowedAsync(object userState) {
            if ((this.digiEAR_QueryAnalyzerAllowedOperationCompleted == null)) {
                this.digiEAR_QueryAnalyzerAllowedOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_QueryAnalyzerAllowedOperationCompleted);
            }
            this.InvokeAsync("digiEAR_QueryAnalyzerAllowed", new object[0], this.digiEAR_QueryAnalyzerAllowedOperationCompleted, userState);
        }
        
        private void OndigiEAR_QueryAnalyzerAllowedOperationCompleted(object arg) {
            if ((this.digiEAR_QueryAnalyzerAllowedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_QueryAnalyzerAllowedCompleted(this, new digiEAR_QueryAnalyzerAllowedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_GetPatInfo", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_GetPatInfo(string patString, out uint iAudioLen, out string langName, out byte langVersion) {
            object[] results = this.Invoke("digiEAR_GetPatInfo", new object[] {
                        patString});
            iAudioLen = ((uint)(results[1]));
            langName = ((string)(results[2]));
            langVersion = ((byte)(results[3]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_GetPatInfoAsync(string patString) {
            this.digiEAR_GetPatInfoAsync(patString, null);
        }
        
        /// <remarks/>
        public void digiEAR_GetPatInfoAsync(string patString, object userState) {
            if ((this.digiEAR_GetPatInfoOperationCompleted == null)) {
                this.digiEAR_GetPatInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_GetPatInfoOperationCompleted);
            }
            this.InvokeAsync("digiEAR_GetPatInfo", new object[] {
                        patString}, this.digiEAR_GetPatInfoOperationCompleted, userState);
        }
        
        private void OndigiEAR_GetPatInfoOperationCompleted(object arg) {
            if ((this.digiEAR_GetPatInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_GetPatInfoCompleted(this, new digiEAR_GetPatInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cyberasiatech.com/digiEAR/XmlWebServices/")]
    public enum DEERRORCODE_TAG {
        
        /// <remarks/>
        DE_SUCCESS,
        
        /// <remarks/>
        DEE_ERROR,
        
        /// <remarks/>
        DEE_API_NOT_INITIALIZED,
        
        /// <remarks/>
        DEE_API_ALREADY_INITIALIZED,
        
        /// <remarks/>
        DEE_CACHE_INSUFFICIENT_MEMORY,
        
        /// <remarks/>
        DEE_CACHE_SIZE_TOO_SMALL,
        
        /// <remarks/>
        DEE_CACHE_FULL,
        
        /// <remarks/>
        DEE_FILE_OPEN_ERROR,
        
        /// <remarks/>
        DEE_FILE_READ_ERROR,
        
        /// <remarks/>
        DEE_FILE_INCORRECT_FORMAT,
        
        /// <remarks/>
        DEE_FILE_VERSION_MISMATCH,
        
        /// <remarks/>
        DEE_FILE_CREATE_ERROR,
        
        /// <remarks/>
        DEE_FILE_WRITE_ERROR,
        
        /// <remarks/>
        DEE_FILE_INVALID_FILENAME,
        
        /// <remarks/>
        DEE_FILE_NOT_FOUND,
        
        /// <remarks/>
        DEE_FILE_PATH_NOT_FOUND,
        
        /// <remarks/>
        DEE_FILE_READ_ONLY,
        
        /// <remarks/>
        DEE_FILE_NOT_OPEN,
        
        /// <remarks/>
        DEE_FILE_ALREADY_OPEN,
        
        /// <remarks/>
        DEE_INVALID_HANDLE,
        
        /// <remarks/>
        DEE_INVALID_QUERY_STRING,
        
        /// <remarks/>
        DEE_INVALID_MAX_RESULTS,
        
        /// <remarks/>
        DEE_INVALID_DICTIONARY_ENTRY,
        
        /// <remarks/>
        DEE_INVALID_POINTER,
        
        /// <remarks/>
        DEE_INVALID_PARAMETER,
        
        /// <remarks/>
        DEE_INVALID_SAMPLING_FREQUENCY,
        
        /// <remarks/>
        DEE_INVALID_LATENCY,
        
        /// <remarks/>
        DEE_INVALID_SCORE_THRESHOLD,
        
        /// <remarks/>
        DEE_USER_CANCELLED,
        
        /// <remarks/>
        DEE_USER_NOT_EXECUTING,
        
        /// <remarks/>
        DEE_USER_CANNOT_DEINIT,
        
        /// <remarks/>
        DEE_USER_STILL_EXECUTING,
        
        /// <remarks/>
        DEE_INSUFFICIENT_MEMORY,
        
        /// <remarks/>
        DEE_HANDLE_UNAVAILABLE,
        
        /// <remarks/>
        DEE_HANDLE_IN_USE,
        
        /// <remarks/>
        DEE_INTERNAL_ERROR,
        
        /// <remarks/>
        DEE_TIMEOUT,
        
        /// <remarks/>
        DEE_MEDIA_CANNOT_CONVERT,
        
        /// <remarks/>
        DEE_BUFFER_TOO_SMALL,
        
        /// <remarks/>
        DEE_STREAM_NO_DATA_TO_SEARCH,
        
        /// <remarks/>
        DEE_LICENSE_INVALID_EXPIRED,
        
        /// <remarks/>
        DEE_LICENSE_INVALID_KERNEL_VERSION,
        
        /// <remarks/>
        DEE_LICENSE_FEATURE_NOT_AVAIL,
        
        /// <remarks/>
        DEE_LICENSE_INVALID_VERSION,
        
        /// <remarks/>
        DEE_LICENSE_INVALID,
        
        /// <remarks/>
        DEE_LICENSE_WRONG_COMPUTER,
        
        /// <remarks/>
        DEE_LICENSE_TOO_MANY_CPUS,
        
        /// <remarks/>
        DEE_LICENSE_WRONG_PLATFORM,
        
        /// <remarks/>
        DEE_USERDATA_BUFFER_TOO_SMALL,
        
        /// <remarks/>
        DEE_USERDATA_NO_DATA_AVAILABLE,
        
        /// <remarks/>
        DEE_USERDATA_INVALID_OFFSET,
        
        /// <remarks/>
        DEE_USERDATA_BUFFER_INVALID,
        
        /// <remarks/>
        DEE_USERDATA_NOT_SUPPORTED,
        
        /// <remarks/>
        DEE_USERDATA_BUFFER_PARTIALLY_FILLED,
        
        /// <remarks/>
        DEE_LANGUAGE_MISMATCH,
        
        /// <remarks/>
        DEE_SYNC_TEXT_CANNOT_CONVERT,
        
        /// <remarks/>
        DEE_SYNC_TEXT_UNKNOWN_CHARACTER,
        
        /// <remarks/>
        DEE_SYNC_TEXT_MISMATCHED_PAREN,
        
        /// <remarks/>
        DEE_SYNC_TEXT_REQUIRES_FILTERING,
        
        /// <remarks/>
        DEE_MINE_SYNTAX_ERROR,
        
        /// <remarks/>
        DEE_MINE_INSUFFICIENT_DATA,
        
        /// <remarks/>
        DEE_DETECTOR_INVALID_DETECTORID,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_OPERATOR,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_PAU,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_WORD,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_PRO_INDEX,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_PHO_SEQUENCE,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_AUDIOCLIPS,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_ALT_INDEX,
        
        /// <remarks/>
        DEERR_LICENSE_SYSTEM_ERROR,
        
        /// <remarks/>
        DEERR_LICENSE_SYSTEM_NOMORE_LICENSE,
        
        /// <remarks/>
        DEERR_LICENSE_SYSTEM_WAIT_TIMEOUT,
        
        /// <remarks/>
        DEERR_LICENSE_RESPONSE_ERR,
        
        /// <remarks/>
        DEERR_DEAPI_MISMATCH_QUERY_STRING,
        
        /// <remarks/>
        DEERR_SERVER_NOT_IDLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_searchCompletedEventHandler(object sender, digiEAR_searchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_searchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_searchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_search2CompletedEventHandler(object sender, digiEAR_search2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_search2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_search2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_searchOpenHandleCompletedEventHandler(object sender, digiEAR_searchOpenHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_searchOpenHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_searchOpenHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ihSearch {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_searchCloseHandleCompletedEventHandler(object sender, digiEAR_searchCloseHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_searchCloseHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_searchCloseHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_searchCancelCompletedEventHandler(object sender, digiEAR_searchCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_searchCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_searchCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_searchGetStatusCompletedEventHandler(object sender, digiEAR_searchGetStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_searchGetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_searchGetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public float fPercent {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_searchAllowedCompletedEventHandler(object sender, digiEAR_searchAllowedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_searchAllowedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_searchAllowedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_ValidateQueryCompletedEventHandler(object sender, digiEAR_ValidateQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_ValidateQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_ValidateQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string badString {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerGetAllValidSoundBytesCompletedEventHandler(object sender, digiEAR_QueryAnalyzerGetAllValidSoundBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerGetAllValidSoundBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerGetAllValidSoundBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerOpenHandleCompletedEventHandler(object sender, digiEAR_QueryAnalyzerOpenHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerOpenHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerOpenHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ihQanalyzer {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerCloseHandleCompletedEventHandler(object sender, digiEAR_QueryAnalyzerCloseHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerCloseHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerCloseHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerInitialSoundBytesCompletedEventHandler(object sender, digiEAR_QueryAnalyzerInitialSoundBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerInitialSoundBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerInitialSoundBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strQueryString {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strSoundBytes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerGetSoundByteSequenceCompletedEventHandler(object sender, digiEAR_QueryAnalyzerGetSoundByteSequenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerGetSoundByteSequenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerGetSoundByteSequenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strQueryString {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strSoundBytes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public bool binDict {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public float fScore {
            get {
                this.RaiseExceptionIfNecessary();
                return ((float)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompletedEventHandler(object sender, digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerGetAllSoundByteSequencesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet evaluateDS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompletedEventHandler(object sender, digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerGetSoundByteSequenceCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerGetWordCountCompletedEventHandler(object sender, digiEAR_QueryAnalyzerGetWordCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerGetWordCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerGetWordCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public uint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerExamineSearchResultCompletedEventHandler(object sender, digiEAR_QueryAnalyzerExamineSearchResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerExamineSearchResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerExamineSearchResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet examineResultDS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerEvaluateSoundBytesCompletedEventHandler(object sender, digiEAR_QueryAnalyzerEvaluateSoundBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerEvaluateSoundBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerEvaluateSoundBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet evaluateDS {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerFindOptimalCompletedEventHandler(object sender, digiEAR_QueryAnalyzerFindOptimalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerFindOptimalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerFindOptimalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ihProTerms {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_hAllProCompletedEventHandler(object sender, digiEAR_hAllProCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_hAllProCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_hAllProCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_QueryAnalyzerAllowedCompletedEventHandler(object sender, digiEAR_QueryAnalyzerAllowedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_QueryAnalyzerAllowedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_QueryAnalyzerAllowedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_GetPatInfoCompletedEventHandler(object sender, digiEAR_GetPatInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_GetPatInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_GetPatInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public uint iAudioLen {
            get {
                this.RaiseExceptionIfNecessary();
                return ((uint)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string langName {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public byte langVersion {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte)(this.results[3]));
            }
        }
    }
}

#pragma warning restore 1591