//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18449
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.18449。
// 
#pragma warning disable 1591

namespace digiEAR_api_sample.DigiEarIndex {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DEindexSoap", Namespace="http://cyberasiatech.com/digiEAR/XmlWebServices/")]
    public partial class DEindex : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback digiEAR_indexOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexOpenHandleOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexOpenHandle2OperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexCloseHandleOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexEndOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexGetStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexGetResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexGetResult_NoMoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexAllowedOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_indexLimitOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_hAllAcoOperationCompleted;
        
        private System.Threading.SendOrPostCallback digiEAR_hAllAco2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DEindex() {
            this.Url = global::digiEAR_api_sample.Properties.Settings.Default.digiEAR_api_sample_DigiEarIndex_DEindex;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event digiEAR_indexCompletedEventHandler digiEAR_indexCompleted;
        
        /// <remarks/>
        public event digiEAR_indexOpenHandleCompletedEventHandler digiEAR_indexOpenHandleCompleted;
        
        /// <remarks/>
        public event digiEAR_indexOpenHandle2CompletedEventHandler digiEAR_indexOpenHandle2Completed;
        
        /// <remarks/>
        public event digiEAR_indexCloseHandleCompletedEventHandler digiEAR_indexCloseHandleCompleted;
        
        /// <remarks/>
        public event digiEAR_indexCancelCompletedEventHandler digiEAR_indexCancelCompleted;
        
        /// <remarks/>
        public event digiEAR_indexEndCompletedEventHandler digiEAR_indexEndCompleted;
        
        /// <remarks/>
        public event digiEAR_indexGetStatusCompletedEventHandler digiEAR_indexGetStatusCompleted;
        
        /// <remarks/>
        public event digiEAR_indexGetResultCompletedEventHandler digiEAR_indexGetResultCompleted;
        
        /// <remarks/>
        public event digiEAR_indexGetResult_NoMoveCompletedEventHandler digiEAR_indexGetResult_NoMoveCompleted;
        
        /// <remarks/>
        public event digiEAR_indexAllowedCompletedEventHandler digiEAR_indexAllowedCompleted;
        
        /// <remarks/>
        public event digiEAR_indexLimitCompletedEventHandler digiEAR_indexLimitCompleted;
        
        /// <remarks/>
        public event digiEAR_hAllAcoCompletedEventHandler digiEAR_hAllAcoCompleted;
        
        /// <remarks/>
        public event digiEAR_hAllAco2CompletedEventHandler digiEAR_hAllAco2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_index", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_index(string freshFile, string acoName, string targetDir, int ihStream) {
            object[] results = this.Invoke("digiEAR_index", new object[] {
                        freshFile,
                        acoName,
                        targetDir,
                        ihStream});
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexAsync(string freshFile, string acoName, string targetDir, int ihStream) {
            this.digiEAR_indexAsync(freshFile, acoName, targetDir, ihStream, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexAsync(string freshFile, string acoName, string targetDir, int ihStream, object userState) {
            if ((this.digiEAR_indexOperationCompleted == null)) {
                this.digiEAR_indexOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexOperationCompleted);
            }
            this.InvokeAsync("digiEAR_index", new object[] {
                        freshFile,
                        acoName,
                        targetDir,
                        ihStream}, this.digiEAR_indexOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexOperationCompleted(object arg) {
            if ((this.digiEAR_indexCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexCompleted(this, new digiEAR_indexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexOpenHandle", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexOpenHandle(string acoName, out int ihIndex) {
            object[] results = this.Invoke("digiEAR_indexOpenHandle", new object[] {
                        acoName});
            ihIndex = ((int)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexOpenHandleAsync(string acoName) {
            this.digiEAR_indexOpenHandleAsync(acoName, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexOpenHandleAsync(string acoName, object userState) {
            if ((this.digiEAR_indexOpenHandleOperationCompleted == null)) {
                this.digiEAR_indexOpenHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexOpenHandleOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexOpenHandle", new object[] {
                        acoName}, this.digiEAR_indexOpenHandleOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexOpenHandleOperationCompleted(object arg) {
            if ((this.digiEAR_indexOpenHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexOpenHandleCompleted(this, new digiEAR_indexOpenHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexOpenHandle2", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexOpenHandle2(int langHandle, out int ihIndex) {
            object[] results = this.Invoke("digiEAR_indexOpenHandle2", new object[] {
                        langHandle});
            ihIndex = ((int)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexOpenHandle2Async(int langHandle) {
            this.digiEAR_indexOpenHandle2Async(langHandle, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexOpenHandle2Async(int langHandle, object userState) {
            if ((this.digiEAR_indexOpenHandle2OperationCompleted == null)) {
                this.digiEAR_indexOpenHandle2OperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexOpenHandle2OperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexOpenHandle2", new object[] {
                        langHandle}, this.digiEAR_indexOpenHandle2OperationCompleted, userState);
        }
        
        private void OndigiEAR_indexOpenHandle2OperationCompleted(object arg) {
            if ((this.digiEAR_indexOpenHandle2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexOpenHandle2Completed(this, new digiEAR_indexOpenHandle2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexCloseHandle", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexCloseHandle(int ihIndex) {
            object[] results = this.Invoke("digiEAR_indexCloseHandle", new object[] {
                        ihIndex});
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexCloseHandleAsync(int ihIndex) {
            this.digiEAR_indexCloseHandleAsync(ihIndex, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexCloseHandleAsync(int ihIndex, object userState) {
            if ((this.digiEAR_indexCloseHandleOperationCompleted == null)) {
                this.digiEAR_indexCloseHandleOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexCloseHandleOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexCloseHandle", new object[] {
                        ihIndex}, this.digiEAR_indexCloseHandleOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexCloseHandleOperationCompleted(object arg) {
            if ((this.digiEAR_indexCloseHandleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexCloseHandleCompleted(this, new digiEAR_indexCloseHandleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexCancel", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexCancel(int ihIndex) {
            object[] results = this.Invoke("digiEAR_indexCancel", new object[] {
                        ihIndex});
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexCancelAsync(int ihIndex) {
            this.digiEAR_indexCancelAsync(ihIndex, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexCancelAsync(int ihIndex, object userState) {
            if ((this.digiEAR_indexCancelOperationCompleted == null)) {
                this.digiEAR_indexCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexCancelOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexCancel", new object[] {
                        ihIndex}, this.digiEAR_indexCancelOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexCancelOperationCompleted(object arg) {
            if ((this.digiEAR_indexCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexCancelCompleted(this, new digiEAR_indexCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexEnd", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexEnd(int ihIndex) {
            object[] results = this.Invoke("digiEAR_indexEnd", new object[] {
                        ihIndex});
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexEndAsync(int ihIndex) {
            this.digiEAR_indexEndAsync(ihIndex, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexEndAsync(int ihIndex, object userState) {
            if ((this.digiEAR_indexEndOperationCompleted == null)) {
                this.digiEAR_indexEndOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexEndOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexEnd", new object[] {
                        ihIndex}, this.digiEAR_indexEndOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexEndOperationCompleted(object arg) {
            if ((this.digiEAR_indexEndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexEndCompleted(this, new digiEAR_indexEndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexGetStatus", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexGetStatus(int ihIndex, out int iSecond) {
            object[] results = this.Invoke("digiEAR_indexGetStatus", new object[] {
                        ihIndex});
            iSecond = ((int)(results[1]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexGetStatusAsync(int ihIndex) {
            this.digiEAR_indexGetStatusAsync(ihIndex, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexGetStatusAsync(int ihIndex, object userState) {
            if ((this.digiEAR_indexGetStatusOperationCompleted == null)) {
                this.digiEAR_indexGetStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexGetStatusOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexGetStatus", new object[] {
                        ihIndex}, this.digiEAR_indexGetStatusOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexGetStatusOperationCompleted(object arg) {
            if ((this.digiEAR_indexGetStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexGetStatusCompleted(this, new digiEAR_indexGetStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexGetResult", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexGetResult(string freshFile, string targetDir, int ihIndex, int milSec, out int audioLength, out double patSizeMB, out double mediaSizeMB, out string mediaDate) {
            object[] results = this.Invoke("digiEAR_indexGetResult", new object[] {
                        freshFile,
                        targetDir,
                        ihIndex,
                        milSec});
            audioLength = ((int)(results[1]));
            patSizeMB = ((double)(results[2]));
            mediaSizeMB = ((double)(results[3]));
            mediaDate = ((string)(results[4]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexGetResultAsync(string freshFile, string targetDir, int ihIndex, int milSec) {
            this.digiEAR_indexGetResultAsync(freshFile, targetDir, ihIndex, milSec, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexGetResultAsync(string freshFile, string targetDir, int ihIndex, int milSec, object userState) {
            if ((this.digiEAR_indexGetResultOperationCompleted == null)) {
                this.digiEAR_indexGetResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexGetResultOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexGetResult", new object[] {
                        freshFile,
                        targetDir,
                        ihIndex,
                        milSec}, this.digiEAR_indexGetResultOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexGetResultOperationCompleted(object arg) {
            if ((this.digiEAR_indexGetResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexGetResultCompleted(this, new digiEAR_indexGetResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexGetResult_NoMove", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DEERRORCODE_TAG digiEAR_indexGetResult_NoMove(string freshFile, string targetDir, int ihIndex, int milSec, out int audioLength, out double patSizeMB, out double mediaSizeMB, out string mediaDate) {
            object[] results = this.Invoke("digiEAR_indexGetResult_NoMove", new object[] {
                        freshFile,
                        targetDir,
                        ihIndex,
                        milSec});
            audioLength = ((int)(results[1]));
            patSizeMB = ((double)(results[2]));
            mediaSizeMB = ((double)(results[3]));
            mediaDate = ((string)(results[4]));
            return ((DEERRORCODE_TAG)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexGetResult_NoMoveAsync(string freshFile, string targetDir, int ihIndex, int milSec) {
            this.digiEAR_indexGetResult_NoMoveAsync(freshFile, targetDir, ihIndex, milSec, null);
        }
        
        /// <remarks/>
        public void digiEAR_indexGetResult_NoMoveAsync(string freshFile, string targetDir, int ihIndex, int milSec, object userState) {
            if ((this.digiEAR_indexGetResult_NoMoveOperationCompleted == null)) {
                this.digiEAR_indexGetResult_NoMoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexGetResult_NoMoveOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexGetResult_NoMove", new object[] {
                        freshFile,
                        targetDir,
                        ihIndex,
                        milSec}, this.digiEAR_indexGetResult_NoMoveOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexGetResult_NoMoveOperationCompleted(object arg) {
            if ((this.digiEAR_indexGetResult_NoMoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexGetResult_NoMoveCompleted(this, new digiEAR_indexGetResult_NoMoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexAllowed", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int digiEAR_indexAllowed() {
            object[] results = this.Invoke("digiEAR_indexAllowed", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexAllowedAsync() {
            this.digiEAR_indexAllowedAsync(null);
        }
        
        /// <remarks/>
        public void digiEAR_indexAllowedAsync(object userState) {
            if ((this.digiEAR_indexAllowedOperationCompleted == null)) {
                this.digiEAR_indexAllowedOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexAllowedOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexAllowed", new object[0], this.digiEAR_indexAllowedOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexAllowedOperationCompleted(object arg) {
            if ((this.digiEAR_indexAllowedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexAllowedCompleted(this, new digiEAR_indexAllowedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_indexLimit", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int digiEAR_indexLimit() {
            object[] results = this.Invoke("digiEAR_indexLimit", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_indexLimitAsync() {
            this.digiEAR_indexLimitAsync(null);
        }
        
        /// <remarks/>
        public void digiEAR_indexLimitAsync(object userState) {
            if ((this.digiEAR_indexLimitOperationCompleted == null)) {
                this.digiEAR_indexLimitOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_indexLimitOperationCompleted);
            }
            this.InvokeAsync("digiEAR_indexLimit", new object[0], this.digiEAR_indexLimitOperationCompleted, userState);
        }
        
        private void OndigiEAR_indexLimitOperationCompleted(object arg) {
            if ((this.digiEAR_indexLimitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_indexLimitCompleted(this, new digiEAR_indexLimitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_hAllAco", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet digiEAR_hAllAco() {
            object[] results = this.Invoke("digiEAR_hAllAco", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_hAllAcoAsync() {
            this.digiEAR_hAllAcoAsync(null);
        }
        
        /// <remarks/>
        public void digiEAR_hAllAcoAsync(object userState) {
            if ((this.digiEAR_hAllAcoOperationCompleted == null)) {
                this.digiEAR_hAllAcoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_hAllAcoOperationCompleted);
            }
            this.InvokeAsync("digiEAR_hAllAco", new object[0], this.digiEAR_hAllAcoOperationCompleted, userState);
        }
        
        private void OndigiEAR_hAllAcoOperationCompleted(object arg) {
            if ((this.digiEAR_hAllAcoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_hAllAcoCompleted(this, new digiEAR_hAllAcoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cyberasiatech.com/digiEAR/XmlWebServices/digiEAR_hAllAco2", RequestNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", ResponseNamespace="http://cyberasiatech.com/digiEAR/XmlWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet digiEAR_hAllAco2() {
            object[] results = this.Invoke("digiEAR_hAllAco2", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void digiEAR_hAllAco2Async() {
            this.digiEAR_hAllAco2Async(null);
        }
        
        /// <remarks/>
        public void digiEAR_hAllAco2Async(object userState) {
            if ((this.digiEAR_hAllAco2OperationCompleted == null)) {
                this.digiEAR_hAllAco2OperationCompleted = new System.Threading.SendOrPostCallback(this.OndigiEAR_hAllAco2OperationCompleted);
            }
            this.InvokeAsync("digiEAR_hAllAco2", new object[0], this.digiEAR_hAllAco2OperationCompleted, userState);
        }
        
        private void OndigiEAR_hAllAco2OperationCompleted(object arg) {
            if ((this.digiEAR_hAllAco2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.digiEAR_hAllAco2Completed(this, new digiEAR_hAllAco2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cyberasiatech.com/digiEAR/XmlWebServices/")]
    public enum DEERRORCODE_TAG {
        
        /// <remarks/>
        DE_SUCCESS,
        
        /// <remarks/>
        DEE_ERROR,
        
        /// <remarks/>
        DEE_API_NOT_INITIALIZED,
        
        /// <remarks/>
        DEE_API_ALREADY_INITIALIZED,
        
        /// <remarks/>
        DEE_CACHE_INSUFFICIENT_MEMORY,
        
        /// <remarks/>
        DEE_CACHE_SIZE_TOO_SMALL,
        
        /// <remarks/>
        DEE_CACHE_FULL,
        
        /// <remarks/>
        DEE_FILE_OPEN_ERROR,
        
        /// <remarks/>
        DEE_FILE_READ_ERROR,
        
        /// <remarks/>
        DEE_FILE_INCORRECT_FORMAT,
        
        /// <remarks/>
        DEE_FILE_VERSION_MISMATCH,
        
        /// <remarks/>
        DEE_FILE_CREATE_ERROR,
        
        /// <remarks/>
        DEE_FILE_WRITE_ERROR,
        
        /// <remarks/>
        DEE_FILE_INVALID_FILENAME,
        
        /// <remarks/>
        DEE_FILE_NOT_FOUND,
        
        /// <remarks/>
        DEE_FILE_PATH_NOT_FOUND,
        
        /// <remarks/>
        DEE_FILE_READ_ONLY,
        
        /// <remarks/>
        DEE_FILE_NOT_OPEN,
        
        /// <remarks/>
        DEE_FILE_ALREADY_OPEN,
        
        /// <remarks/>
        DEE_INVALID_HANDLE,
        
        /// <remarks/>
        DEE_INVALID_QUERY_STRING,
        
        /// <remarks/>
        DEE_INVALID_MAX_RESULTS,
        
        /// <remarks/>
        DEE_INVALID_DICTIONARY_ENTRY,
        
        /// <remarks/>
        DEE_INVALID_POINTER,
        
        /// <remarks/>
        DEE_INVALID_PARAMETER,
        
        /// <remarks/>
        DEE_INVALID_SAMPLING_FREQUENCY,
        
        /// <remarks/>
        DEE_INVALID_LATENCY,
        
        /// <remarks/>
        DEE_INVALID_SCORE_THRESHOLD,
        
        /// <remarks/>
        DEE_USER_CANCELLED,
        
        /// <remarks/>
        DEE_USER_NOT_EXECUTING,
        
        /// <remarks/>
        DEE_USER_CANNOT_DEINIT,
        
        /// <remarks/>
        DEE_USER_STILL_EXECUTING,
        
        /// <remarks/>
        DEE_INSUFFICIENT_MEMORY,
        
        /// <remarks/>
        DEE_HANDLE_UNAVAILABLE,
        
        /// <remarks/>
        DEE_HANDLE_IN_USE,
        
        /// <remarks/>
        DEE_INTERNAL_ERROR,
        
        /// <remarks/>
        DEE_TIMEOUT,
        
        /// <remarks/>
        DEE_MEDIA_CANNOT_CONVERT,
        
        /// <remarks/>
        DEE_BUFFER_TOO_SMALL,
        
        /// <remarks/>
        DEE_STREAM_NO_DATA_TO_SEARCH,
        
        /// <remarks/>
        DEE_LICENSE_INVALID_EXPIRED,
        
        /// <remarks/>
        DEE_LICENSE_INVALID_KERNEL_VERSION,
        
        /// <remarks/>
        DEE_LICENSE_FEATURE_NOT_AVAIL,
        
        /// <remarks/>
        DEE_LICENSE_INVALID_VERSION,
        
        /// <remarks/>
        DEE_LICENSE_INVALID,
        
        /// <remarks/>
        DEE_LICENSE_WRONG_COMPUTER,
        
        /// <remarks/>
        DEE_LICENSE_TOO_MANY_CPUS,
        
        /// <remarks/>
        DEE_LICENSE_WRONG_PLATFORM,
        
        /// <remarks/>
        DEE_USERDATA_BUFFER_TOO_SMALL,
        
        /// <remarks/>
        DEE_USERDATA_NO_DATA_AVAILABLE,
        
        /// <remarks/>
        DEE_USERDATA_INVALID_OFFSET,
        
        /// <remarks/>
        DEE_USERDATA_BUFFER_INVALID,
        
        /// <remarks/>
        DEE_USERDATA_NOT_SUPPORTED,
        
        /// <remarks/>
        DEE_USERDATA_BUFFER_PARTIALLY_FILLED,
        
        /// <remarks/>
        DEE_LANGUAGE_MISMATCH,
        
        /// <remarks/>
        DEE_SYNC_TEXT_CANNOT_CONVERT,
        
        /// <remarks/>
        DEE_SYNC_TEXT_UNKNOWN_CHARACTER,
        
        /// <remarks/>
        DEE_SYNC_TEXT_MISMATCHED_PAREN,
        
        /// <remarks/>
        DEE_SYNC_TEXT_REQUIRES_FILTERING,
        
        /// <remarks/>
        DEE_MINE_SYNTAX_ERROR,
        
        /// <remarks/>
        DEE_MINE_INSUFFICIENT_DATA,
        
        /// <remarks/>
        DEE_DETECTOR_INVALID_DETECTORID,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_OPERATOR,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_PAU,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_WORD,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_PRO_INDEX,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_PHO_SEQUENCE,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_AUDIOCLIPS,
        
        /// <remarks/>
        DEE_TERMANALYSIS_INVALID_ALT_INDEX,
        
        /// <remarks/>
        DEERR_LICENSE_SYSTEM_ERROR,
        
        /// <remarks/>
        DEERR_LICENSE_SYSTEM_NOMORE_LICENSE,
        
        /// <remarks/>
        DEERR_LICENSE_SYSTEM_WAIT_TIMEOUT,
        
        /// <remarks/>
        DEERR_LICENSE_RESPONSE_ERR,
        
        /// <remarks/>
        DEERR_DEAPI_MISMATCH_QUERY_STRING,
        
        /// <remarks/>
        DEERR_SERVER_NOT_IDLE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexCompletedEventHandler(object sender, digiEAR_indexCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexOpenHandleCompletedEventHandler(object sender, digiEAR_indexOpenHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexOpenHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexOpenHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ihIndex {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexOpenHandle2CompletedEventHandler(object sender, digiEAR_indexOpenHandle2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexOpenHandle2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexOpenHandle2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ihIndex {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexCloseHandleCompletedEventHandler(object sender, digiEAR_indexCloseHandleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexCloseHandleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexCloseHandleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexCancelCompletedEventHandler(object sender, digiEAR_indexCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexEndCompletedEventHandler(object sender, digiEAR_indexEndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexEndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexEndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexGetStatusCompletedEventHandler(object sender, digiEAR_indexGetStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexGetStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexGetStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int iSecond {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexGetResultCompletedEventHandler(object sender, digiEAR_indexGetResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexGetResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexGetResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int audioLength {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public double patSizeMB {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public double mediaSizeMB {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string mediaDate {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexGetResult_NoMoveCompletedEventHandler(object sender, digiEAR_indexGetResult_NoMoveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexGetResult_NoMoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexGetResult_NoMoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DEERRORCODE_TAG Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DEERRORCODE_TAG)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int audioLength {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public double patSizeMB {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public double mediaSizeMB {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string mediaDate {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexAllowedCompletedEventHandler(object sender, digiEAR_indexAllowedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexAllowedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexAllowedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_indexLimitCompletedEventHandler(object sender, digiEAR_indexLimitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_indexLimitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_indexLimitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_hAllAcoCompletedEventHandler(object sender, digiEAR_hAllAcoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_hAllAcoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_hAllAcoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void digiEAR_hAllAco2CompletedEventHandler(object sender, digiEAR_hAllAco2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class digiEAR_hAllAco2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal digiEAR_hAllAco2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591